sudo: false

language: node_js
node_js:
  - 12

env:
  jobs:
    - MONGO_URI="mongodb://travis:test@localhost:27017/nestdragon"

services:
  - mongodb

before_script:
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
  - npm install

script:
  - npm run lint
  - npm run test:e2e

notifications:
  email: false
